ARMmbed/ble-nrf51822

nordic-sdk/components/softdevice/s110/headers/nrf_svc.h

This fix was previously in the library but was lost when porting over to new SDK

Fix for GCC lost in SDK v8.0 update

---

source/btle/btle.cpp
source/nordic-sdk/components/softdevice/s130/include/ble_gap.h

This humble change adds backward-compatibility for S110 to the nRF51822 API. It assumes that the build system will defines either *MCU_NORDIC_16K_S110* or *MCU_NORDIC_32K_S110* when S110 is enabled instead of the default S130.
Currently, the only major difference between S110 and S130 headers is the added "role" parameter in the ble_gap_evt_connected_t structure, sent by the softdevice after a connection. These patches handle this case.
Please note that this is only for build compatibility. Applications built for S110 will work, but their behaviour when attempting to use S130 features, such as GAP scanning, is undefined. This will need some additional work to return a clean "not implemented" value.

Add S110 SoftDevice compatibility

---

source/btle/btle.cpp
source/btle/btle_discovery.cpp
source/nRF5xGap.h
source/nRF5xGattClient.cpp
source/nRF5xGattClient.h

S110 compatibility is already present, but this patch adds proper handling
of observer/central related features:
* Gap::startScan will return BLE_ERRROR_NOT_IMPLEMENTED (instead of
PARAM_OUT_OF_RANGE)
* nRF5xGattClient uses the default GattClient implementation when S110 is
in use. All if its methods return NOT_IMPLEMENTED.
Example: for an application that acts as both a central and a peripheral,
using S110 will make the ble.gap().startScan() call return
BLE_ERROR_NOT_IMPLEMENTED, and advertisement features will continue
running normally.
In addition, with GCC, this patch will free 344 bytes of RAM and 2504
bytes of flash.

Disable GattClient features when using S110 SoftDevice

---

source/btle/btle.cpp
source/btle/btle_discovery.cpp
source/nRF5xGap.h
source/nRF5xGattClient.cpp
source/nRF5xGattClient.h
source/nordic-sdk/components/softdevice/s130/include/ble_gap.h

Those macros are defined by mbed SDK in targets.py. They changed from
MCU_NORDIC_xxx_S110 to MCU_NRF51_xxx_S110. Update the #ifdefs accordingly.

Update S110 detection macros

---

source/nRF5xGattServer.cpp

your patch fixed (works with gapConnectionHandle)
sd_ble_gatts_hvx still wrong sometimes on triangle test exemple but it looks like a s130 issue.

rgrover patch fixed

---

source/btle/btle.cpp
source/btle/btle_discovery.cpp
source/nRF5xGap.h
source/nRF5xGattClient.cpp
source/nRF5xGattClient.h
source/nordic-sdk/components/softdevice/s130/include/ble_gap.h

The mbed SDK actually prefixes all labels from targets.py with "TARGET_".
Update our detection macros accordingly.
---
Hi Rohit,
This is embarrassing. The mbed SDK still doesn't select the macros that allow to remove Central features, when building with a S110 SoftDevice.
I noticed this while investigating [another issue](https://github.com/mbedmicro/mbed/pull/1373) in the live IDE. I now have a simple [test case](https://developer.mbed.org/users/jbru/code/NRF51_SoftDevice_test_case/) to check that the SoftDevice in use matches the build options.
I built it locally with workspace_tools/singletest.py and this patch, to ensure that my two patches will have the right behaviour once integrated into the live IDE.
Hopefully, this should do the trick.

Update S110 detection macros, again

---

source/nRF5xGap.cpp

This will reuse the scan parameters set by ```Gap->setScanParams```.

When connecting, if no scanning parameters are passed, use values from Gap parent.

---

source/btle/custom/custom_helper.cpp
source/nRF5xGattClient.cpp
source/nRF5xSecurityManager.cpp
source/nordic-sdk/components/ble/device_manager/config/device_manager_cnfg.h

Moved GattSecurityManager and GattClient to be allocated dynamically and
reduced the size of some arrays to increase memory savings.

Introduced changes for memory savings

---

source/nRF5xGattServer.cpp

Currently it just blindly writes beyond the end of the array, leading to impossible-to-find bugs.
It doesn't help that the limit on the number of characteristics doesn't seem to be documented anywhere.
Sorry github's editor won't let me use spaces so there may be some correct indentation characters in there (i.e. tabs!). I did try.

Error check number of characteristics

---

source/nRF5xn.cpp

Otherwise, once the BLE API has been shutdown, there is no way to initialize it again. Init will always fail.

Ensure that the initialization flags is set to false if the BLE stack is shutdown properly.

---

source/nordic-sdk/components/libraries/bootloader_dfu/bootloader_util_arm.c

The assemble sequence within an mbedOS application that starts the nordic bootloader was being modified by the compiler. The result is that DFU enabled applications could never start the bootloader correctly. This is because the GCC compiler was translating a MOV instruction into a ADDS, which sets the conditional flags in APSR before a conditional branch was executed. The result of the incorrect branch caused the program to believe that it was in interrupt mode when this was not the case.
@rgrover

Fix assembly sequence to start bootloader in GCC

---

LICENSE
bootloader/softdevice_nrf51822_licence_agreement.txt
module.json
softdevice_nrf51822_licence_agreement.txt

note: we need the softdevice in this module because it is shared with mbed-classic. This is where the mbed-classic toolchain expects to find the SD.
@LiyouZhou

add Nordic's license agreement.

---

source/nRF5xGap.cpp

https://developer.nordicsemi.com/nRF51_SDK/nRF51_SDK_v8.x.x/doc/8.1.0/s130/html/a01260.html#gaaf0deb48ed35d1e6ede6222dd72fe12c

Fixed bug in nRF5xGap.setAddress where random adresses where not set properly.

---

source/btle/custom/custom_helper.cpp
source/btle/custom/custom_helper.h
source/nRF5xGattServer.cpp

Previously the concepts of initLength and lenth were clearly separated. However, this was at the cost of registering all characteristics in the SoftDevice as having variable length. Clearly, this is not the desired behaviour. Therefore, an additional field '_hasVariableLen' is added to the GattAttribute to address the problem. Also, the GattAttribute and GattCharacteristic constructors have been modified to take a boolean that sets '_hasVariableLen'.
**NOTE:** Changes to this module will cause projects to fail the build stage if changes to the BLE_API are not published first.
@rgrover

Allow GattAttributes to have variable length

---

source/nRF5xServiceDiscovery.cpp

In BLE::UUID, uuids are stored and handled little endian. This PR preserves the endianness returned by the Nordic Softdevice during discovery.

Fixed endianness bug in nRF5xServiceDiscovery::processDiscoverUUIDResponse so it is consistent with BLE API.

---

source/supress-warnings.cmake

Add -Wno-unused-function to supress-warnings.cmake

---

source/nRF5xGap.cpp
source/nRF5xGap.h
source/nRF5xGattServer.cpp
source/nRF5xn.cpp

Replace all deprecated inclusions of mbed.h for mbed-drivers/mbed.h when using
mbed OS. Applications should compile for mbed classic.

Replace deprecated inclusions of mbed.h

---

source/nRF5xn.cpp
source/nRF5xn.h

This should fix the Hard Fault that generated from the following code sequence:
```
ble.init();
ble.shutdown();
```
@LiyouZhou @pan-

Fix shutdown of Gap instance to avoid NULL refs

---

module.json
source/btle/btle_security.cpp
source/btle/btle_security.h
source/nRF5xGap.cpp
source/nRF5xGap.h
source/nRF5xSecurityManager.h

This pull request introduces an implementation for nRF51822 based devices to use the whitelisting features of the underlying stack. All functionality introduced by the stack is supported with the exception of initiator whitelisting.
**NOTE:** This pull request must be merged AFTER https://github.com/ARMmbed/nrf51-sdk/pull/15 is published since if uses a couple of functions from the Nordic SDK that were not present in the nrf51-sdk yotta module.
**NOTE:** This pull request lacks the implementation of reset() in nRF5xGap that clears the whitelist on a call to `ble.shutdown()`.
**NOTE:** Both the whitelisting API and this implementation are experimental and might change in the near future.
@pan-

Add implementation of experimental whitelisting API

---

source/btle/btle_security.cpp
source/btle/btle_security.h
source/nRF5xSecurityManager.h

Finish the implementation of the new function getAddressesFromBondTable() in
SecurityManager that returns a table with a list of addresses from the peers
in the bond table.
@pan-

Finish implementation of getAddressesFromBondTable

---

source/nRF5xGap.cpp

Remove most updates to Gap::state from ble-nrf51822 and put them in Gap itself.
@pan-

Remove Gap::state updates from this module

---

source/nRF5xGattServer.cpp

The variable descriptorCount is used as an index, and this index is used to set
the handle of the last registered descriptor.
Prior to this fix, descriptorCount was incremented before the handle the update
of the handle of a characteristics.
Short story, all characteristics descriptors handle were equaols to 0 instead
of the actual value.

Fix incorrect handles of characteristics descriptors.

---

source/btle/btle.cpp

Now methods that are exclusive to Softdevice S130 are not called when S110 (legacy mode) it's used.
This fix solves the following errors:
-error: 'class nRF5xGattClient' has no member named 'characteristicDescriptorDiscoverer'
-error: 'class nRF5xGattClient' has no member named 'discovery'
Compiled on ubuntu 14.04 with yotta on target mkit-gcc

Fix for compilation errors with S110 softdevice in btle.cpp

---

source/nRF5xGattServer.cpp

While fixing the return value, nRF5xGattServer::write will also return a
more meaningful result in case of faillure than just
BLE_ERROR_PARAM_OUT_OF_RANGE.
This PR fix #119 .
@rgrover could you review this ?

Fix return value of nRF5xGattServer::write.

---

source/btle/btle.h
source/btle/custom/custom_helper.h
source/nRF5xGap.h
source/nRF5xGattServer.h
source/nRF5xServiceDiscovery.h

This change has been introduced in the SDK to mitigate
compilation issues with mbed-classic.
see https://github.com/ARMmbed/nrf51-sdk/pull/26.

Replace inclusion of nordic header ble.h into nrf_ble.h
